language: php

dist: trusty

sudo: required

php:
    - 7.3

services:
    - memcached

cache:
    directories:
        - vendor
        - bin

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - composer install --no-interaction --prefer-dist

before_script:
    - bin/console doctrine:database:create --env=test -vvv # Have to be run with debug = true, to omit generating proxies before setting up the database
    - bin/console doctrine:schema:create --env=test -vvv
    - bin/console cache:warmup --env=test --no-debug -vvv

script:
    - echo "Running phpunit"
    - vendor/bin/simple-phpunit
    - vendor/bin/yaml-lint ./
